### ISSUE TITLE
您好

### ISSUE THREAD

**Issue by rianjskis** [Gzxhwq/OpenWrt-Actions#2]
在您提交的passwall2中服务端搭建vless等节点开启多路复用，使用安卓端singbox会提示：
inbound/tun[tun-in]: upload: unsupported address download: http2: client connection force closed via ClientConn.Close，请问您能解决这个错误让多路复用可用吗，感谢

**Comment by rianjskis** [comment]
服务端开启多路复用跟TCP Brutal在配置文件中没有显示出来，是这个原因报错导致使用不了

**Comment by Gzxhwq** [comment]
粘贴的时候搞错了位置，已经修了，等合并
